steps:
  # Lints the codebase
  - name: python:3.12.6
    id: lint_proxy_service
    entrypoint: "sh"
    args:
      - "-c"
      - |
        pip install --upgrade pip
        pip install poetry==2.1.2
        echo "*************************************************************"
        echo "* Linting the codebase...                                   *"
        echo "*************************************************************"
        make lint
        make megalint

  # # Tests the codebase
  # name: python:3.12.6
  # id: "test_proxy_service"
  # entrypoint: "sh"
  # args:
  #   - "-c"
  #   - |
  #     echo "*************************************************************"
  #     echo "* Testing the codebase...                                   *"
  #     echo "*************************************************************"
  #     make test

  # # Plans the Terraform configuration
  # name: "hashicorp/terraform:latest"
  # id: "plan_terraform_for_proxy_service"
  # entrypoint: "sh"
  # args:
  #   - "-c"
  #   - |
  #     echo "*************************************************************"
  #     echo "* Planning the Terraform configuration...                   *"
  #     echo "*************************************************************"

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
