steps:
  # Run Megalinter to lint the codebase
  - name: "gcr.io/cloud-builders/docker"
    id: "megalinter"
    args: ["run", "--platform", "linux/amd64", "--rm", "-v", "/var/run/docker.sock:/var/run/docker.sock:rw", "-v", "\"$(pwd)\":/tmp/lint:rw", "ghcr.io/oxsecurity/megalinter-python:v9.1.0"]

timeout: "1800s"

options:
  logging: CLOUD_LOGGING_ONLY
