steps:
  # Run Megalinter to lint the codebase
  - name: "gcr.io/cloud-builders/docker"
    id: "megalinter"
    args: ["run", "--platform", "linux/amd64", "--rm", "-v", "/var/run/docker.sock:/var/run/docker.sock:rw", "-v", "/workspace:/tmp/lint:rw", "ghcr.io/oxsecurity/megalinter-python:v9.1.0"]

  # Install Pip and Poetry
  - name: "python:3.12.6"
    id: install-pip-and-poetry
    entrypoint: "pip"
    args: ["install", "--upgrade", "pip", "poetry==2.1.2"]

  # Install development dependencies and run test
  - name: "ubuntu"
    id: install-dev-dependencies-and-run-test
    entrypoint: "sh"
    args:
      - "c"
      - |
        make install-dev
        make test

timeout: "1800s"

options:
  logging: CLOUD_LOGGING_ONLY
