steps:
  # Build the container image using the sanitized CLEAN_TAG as the tag
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}:${_CLEAN_TAG}", "."]

  # Push the image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}:${_CLEAN_TAG}"]

substitutions:
  _CLEAN_TAG: ${BRANCH_NAME}//[^A-Za-z0-9_.-]/-

options:
  logging: CLOUD_LOGGING_ONLY
