steps:
  # Builds the Docker image
  - name: docker
    id: build_converter_service_image
    dir: cir-converter-service
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ $_ENV = "staging" ]; then
          echo "*************************************************************"
          echo "* Building Docker image for environment...                  *"
          echo "*************************************************************"

          docker build -t "$_EQ_CIR_CONVERTER_SERVICE_IMAGE_REPO:${SHORT_SHA}" .
        else
          echo "Build skipped for non-staging environment."
        fi

  # Pushes the Docker image to Artifact Registry
  - name: docker
    id: push_converter_service_image
    dir: cir-converter-service
    entrypoint: "sh"
    waitFor: build_converter_service_image
    args:
      - "-c"
      - |
        if [ $_ENV = "staging" ]; then
          echo "*************************************************************"
          echo "* Pushing Docker image to Artifact Registry...              *"
          echo "*************************************************************"

          docker push "$_EQ_CIR_CONVERTER_SERVICE_IMAGE_REPO:${SHORT_SHA}"
        else
          echo "Push skipped for non-staging environment."
        fi
timeout: 1800s
